const words = [
    { word: 'APPLE', hint: 'A common fruit, often associated with a tech giant' },
    { word: 'LONDON', hint: 'The capital city of the United Kingdom' },
    { word: 'PYRAMID', hint: 'A structure found in Egypt, built by ancient civilizations' },
    { word: 'DINOSAUR', hint: 'A type of creature that lived millions of years ago' },
    { word: 'BUTTERFLY', hint: 'An insect that starts life as a caterpillar' },
    { word: 'MOON', hint: 'The natural satellite of the Earth, visible at night' },
    { word: "Avocado", hint: "What is the main ingredient in guacamole?" },
    { word: "Seven", hint: "In the story of Snow White, how many dwarfs are there?" },
    { word: "Zeus", hint: "Who is the king of the gods in Greek mythology?" },
    { word: 'CHOCOLATE', hint: 'A sweet treat that is a popular flavor in ice cream' },
    { word: 'SUN', hint: 'The star at the center of our solar system' },
    { word: 'ELEPHANT', hint: 'A large mammal known for its long trunk' },
    { word: 'BICYCLE', hint: 'A vehicle with two wheels that you pedal' },
    { word: 'PIANO', hint: 'A large musical instrument with black and white keys' },
    { word: 'RAINBOW', hint: 'A colorful arc that appears in the sky after rain' },
    { word: 'VOLCANO', hint: 'A mountain that can erupt with lava' },
    { word: 'OCEAN', hint: 'A large body of salt water that covers most of the Earth' },
    { word: 'PIZZA', hint: ' A popular food that originated from Italy' },
    { word: "Nectar", hint: "What do bees collect to make honey?" },
    { word: "Earth", hint: "Which planet is known as the “Blue Planet”?" },
    { word: "Square", hint: "Which geometric shape has four equal sides and four right angles?" },
    { word: "Rice", hint: "What is the main ingredient in the dish sushi?" }, 
    { word: "Ganymede", hint: "What is the name of the largest moon of Jupiter?" },
    { word: "Uranus", hint: "What is the only planet that rotates on its side?" },
    { word: "Rats", hint: "What animal is known to laugh and has been proven to have a sense of humor?" },    
]

export default words